"""
Configurable reward shaper for Phase 7 Flappy Bird RL.

Wraps the raw environment reward with configurable components:
    +pipe_reward      on each successfully passed pipe
    +survival_reward  per timestep alive
    -collision_penalty on terminal collision

The agent's sensory input (9-channel visual sensor) does NOT receive
privileged information (bird_vy, exact pipe_x, gap_center, optimal action).
Reward is generated by the environment and supplied separately.
"""

from __future__ import annotations
from typing import Dict, Any, Tuple


class FlappyRewardShaper:
    """
    Configurable Flappy Bird reward function for Phase 7 RL.

    Reward components (all configurable):
        R_t = pipe_reward * I(pipe_passed)
             + survival_reward * I(alive)
             + collision_penalty * I(collision)

    Default values produce a sparse-ish reward that requires the agent
    to actually pass pipes to receive meaningful feedback.
    """

    def __init__(
        self,
        pipe_reward: float = 1.0,
        survival_reward: float = 0.001,
        collision_penalty: float = -1.0,
    ):
        self.pipe_reward       = pipe_reward
        self.survival_reward   = survival_reward
        self.collision_penalty = collision_penalty

    def shape(self, env_reward: float, info: Dict[str, Any], done: bool) -> float:
        """
        Compute shaped reward from raw environment output.

        Args:
            env_reward: Raw reward from FlappyEnvironment.step()
            info:       Info dict from FlappyEnvironment.step()
            done:       Episode done flag

        Returns:
            Shaped scalar reward.
        """
        r = 0.0

        # Pipe-passing reward
        if info.get("obstacle_passed", False):
            r += self.pipe_reward

        # Per-step survival bonus
        if not done:
            r += self.survival_reward

        # Collision penalty
        if info.get("collision", False):
            r += self.collision_penalty

        return float(r)

    def __repr__(self) -> str:
        return (
            f"FlappyRewardShaper("
            f"pipe={self.pipe_reward}, "
            f"survival={self.survival_reward}, "
            f"collision={self.collision_penalty})"
        )
